pycons-site/registration/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from .views import *

app_name = 'registration'

urlpatterns = [  
    path('create_profile/', login_required(CreateProfileView.as_view()), name='create_profile'),
    path('update/<str:pk>/', UpdateProfileView.as_view(), name='profile_update'),  
    path('', login_required(ProfileView.as_view()), name='profile_home'),
    re_path('password_change/(?P<pk>\d+)/', login_required(PasswordView.as_view()), name='password_change'),
    re_path('login_details/(?P<pk>\d+)/', login_required(UpdateLoginView.as_view()), name='login_details'),
    path('profile_updated/', login_required(SuccessView.as_view()), name='profile_update'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pycons-site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404, handler500  
from django_robohash.views import robohash 
from django.views.static import serve  
from django.views.generic import RedirectView


urlpatterns = [

#Apps
    path('', include('home.urls', namespace='homepage')),
    path('<int:year>/', include([
        path('', include('home.urls')),
        path('about/', include('about.urls')),
        path('speakers/', include('speakers.urls')),
        path('schedule/', include('conference_schedule.urls')),
        path('our-sponsors/', include('sponsors.urls', namespace='sponsors')),
        path('talks/', include('talks.urls', namespace='talks')),
        path('coc/', include('coc.urls')),
        path('sponsor-us/', include('sponsor_us.urls', namespace='sponsor_us')),
        # Add more apps here following the same pattern
        path('h&g/', include('health_safety_guideline.urls', namespace='health_safety_guideline')),
        path('fin-aid/', include('fin_aid.urls', namespace='fin_aid')),
        path('privacy-policy/', include('privacypolicy.urls', namespace='privacypolicy')),
        path('tickets/', include('tickets.urls', namespace='ticket')),

        
        #Leave this last to catch all pages
        path('', include('cms.urls')),   
    ])),
    path('organizers/', admin.site.urls),  

#Thrid party Apps 
    path('summernote/', include('django_summernote.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/profile/', include('registration.urls', namespace='profiles')),  
    path('accounts/', include('registration.backends.default.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('robohash/<string>/', robohash, name='robohash'),
    path('avatar/', include('avatar.urls')),
    path('markdownx/', include('markdownx.urls')),
    re_path(r'hitcount/', include('hitcount.urls', namespace='hitcount')),


] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.

handler404 = 'home.views.handler404'




# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "PyCon Africa Admin"
admin.site.site_title = "PyCon Africa Admin Portal"
admin.site.index_title = "Welcome to PyCon Africa Portal"

pycons-site/templates/base.html
{% load  %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  
<head>
  <!-- Title -->
  <title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
  
  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'fav/favicon.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'fav/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'fav/site.webmanifest' %}">
  
 <!-- Open Graph Metadata -->
<meta property="og:title" content="{% block og_title %}PyCon Africa{% endblock %}">
<meta property="og:description" content="{% block og_description %}PyCon Africa is the annual gathering for the community using and developing the open-source Python programming language.{% endblock %}">
<meta property="og:image" content="{% block og_image %}https://res.cloudinary.com/pycon-africa/image/upload/v1722977619/website_storage_location/media/pyconafrica.png{% endblock %}">
<meta property="og:url" content="{% block og_url %}{{ request.build_absolute_uri }}{% endblock %}">
<meta property="og:type" content="{% block og_type %}website{% endblock %}">
<meta property="og:site_name" content="{% block og_site_name %}PyCon Africa{% endblock %}">

<!-- Twitter Cards Metadata -->
<meta name="twitter:card" content="{% block twitter_card %}summary_large_image{% endblock %}">
<meta name="twitter:title" content="{% block twitter_title %}PyCon Africa{% endblock %}">
<meta name="twitter:description" content="{% block twitter_description %}PyCon Africa is the annual gathering for the community using and developing the open-source Python programming language.{% endblock %}">
<meta name="twitter:image" content="{% block twitter_image %}https://res.cloudinary.com/pycon-africa/image/upload/v1722977619/website_storage_location/media/pyconafrica.png{% endblock %}">
<meta name="twitter:site" content="{% block twitter_site %}@PyConAfrica{% endblock %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  {% block extra_meta %}{% endblock %}
  
  <!-- Google Fonts -->
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,300,500,600,700,800">

  <!-- CSS Global Compulsory -->
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/bootstrap/bootstrap.min.css' %}">

  <!-- CSS Implementing Plugins -->
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/icon-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/icon-line/css/simple-line-icons.css' %}">
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/icon-hs/style.css' %}">
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/hamburgers/hamburgers.min.css' %}">
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/animate.css' %}">
  <link rel="stylesheet" type="text/css" href="https://site-assets.fontawesome.com/releases/v6.5.1/css/all.css">
  <link rel="stylesheet" type="text/css"  href="https://site-assets.fontawesome.com/releases/v6.1.2/css/all.css"> 
  <link rel="stylesheet" href="{% static 'uni-theme/vendor/fancybox/jquery.fancybox.css' %}">
  <link  rel="stylesheet" href="{% static 'uni-theme/vendor/animate.css' %}">
  <link  rel="stylesheet" href="{% static 'uni-theme/vendor/custombox/custombox.min.css' %}">

  <link  rel="stylesheet" href="{% static 'uni-theme/vendor/dzsparallaxer/dzsparallaxer.css' %}">
  <link  rel="stylesheet" href="{% static 'uni-theme/vendor/dzsparallaxer/dzsscroller/scroller.css' %}">
  <link  rel="stylesheet" href="{% static 'uni-theme/vendor/dzsparallaxer/advancedscroller/plugin.css' %}">
  <link  rel="stylesheet" href="{% static 'uni-theme/vendor/slick-carousel/slick/slick.css' %}">
  <!-- CSS Template -->
  <link rel="stylesheet" href="{% static '2024/css/styles-24.css' %}">

  <!-- CSS Customization -->
  <!--<link rel="stylesheet" href="{% static '2024/css/custom.css' %}">-->
</head>

  <body>





<main>
  

  <!-- Body -->
  {% block content %}
  
  {% endblock %}
  <!-- /Body -->

  {% include '2024/footer.html' %} 

  <a class="js-go-to rounded-0 u-go-to-v1" href="#"
  data-type="fixed"
  data-position='{
    "bottom": 15,
    "right": 15
  }'
  data-offset-top="400"
  data-compensation="#js-header"
  data-show-effect="zoomIn">
 <i class="hs-icon hs-icon-arrow-top"></i>
</a>

</main>



    <!-- JS Global Compulsory -->
    <script src="{% static 'uni-theme/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/jquery-migrate/jquery-migrate.min.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/popper.js/popper.min.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/bootstrap/bootstrap.min.js' %}"></script>

    <!-- JS Implementing Plugins -->
    <script src="{% static 'uni-theme/vendor/appear.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/masonry/dist/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/fancybox/jquery.fancybox.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/slick-carousel/slick/slick.js' %}"></script>
    <script src="{% static 'uni-theme/vendor/gmaps/gmaps.min.js' %}"></script>

    <!-- JS Unify -->
    <script src="{% static '2024/js/hs.core.js' %}"></script>
    <script src="{% static '2024/js/components/hs.header.js' %}"></script>
    <script src="{% static '2024/js/helpers/hs.hamburgers.js' %}"></script>
    <script src="{% static '2024/js/components/hs.scroll-nav.js' %}"></script>
    <script src="{% static '2024/js/components/hs.tabs.js' %}"></script>
    <script src="{% static '2024/js/components/hs.countdown.js' %}"></script>
    <script src="{% static '2024/js/components/hs.carousel.js' %}"></script>
    <script src="{% static '2024/js/components/gmap/hs.map.js' %}"></script>
    <script src="{% static '2024/js/components/hs.go-to.js' %}"></script>




    <div class="shortcode-scripts">
      <!-- JS Unify -->
      <!-- JS Plugins Init. -->
      <script >
        $(document).ready(function () {
          // initialization of carousel
          $.HSCore.components.HSCarousel.init('[class*="js-carousel"]');
        });
      </script> 

               <!-- JS Plugins Init. -->
               <script >
                 $(document).on('ready', function () {
                   // initialization of tabs
                   $.HSCore.components.HSTabs.init('[role="tablist"]');
                 });

                 $(window).on('resize', function () {
                   setTimeout(function () {
                     $.HSCore.components.HSTabs.init('[role="tablist"]');
                   }, 200);
                 });
               </script>
             

    <script  src="{% static 'uni-theme/vendor/dzsparallaxer/dzsparallaxer.js' %}"></script>
    <script  src="{% static 'uni-theme/vendor/dzsparallaxer/dzsscroller/scroller.js' %}"></script>
    <script  src="{% static 'uni-theme/vendor/dzsparallaxer/advancedscroller/plugin.js' %}"></script>
    <!-- JS Customization -->
    <script src="{% static '2024/js/custom.js' %}"></script>

    <!-- JS Plugins Init. -->
    <script>
      // initialization of google map
      function initMap() {
        $.HSCore.components.HSGMap.init('.js-g-map');
      }

      $(document).on('ready', function () {
        // initialization of carousel
        $.HSCore.components.HSCarousel.init('.js-carousel');

        // initialization of header
        $.HSCore.components.HSHeader.init($('#js-header'));
        $.HSCore.helpers.HSHamburgers.init('.hamburger');

        // initialization of tabs
        $.HSCore.components.HSTabs.init('[role="tablist"]');

        // initialization of go to section
        $.HSCore.components.HSGoTo.init('.js-go-to');

        // initialization of countdowns
        var countdowns = $.HSCore.components.HSCountdown.init('.js-countdown', {
          yearsElSelector: '.js-cd-years',
          monthElSelector: '.js-cd-month',
          daysElSelector: '.js-cd-days',
          hoursElSelector: '.js-cd-hours',
          minutesElSelector: '.js-cd-minutes',
          secondsElSelector: '.js-cd-seconds'
        });
      });

      $(window).on('load', function() {
        // initialization of HSScrollNav
        $.HSCore.components.HSScrollNav.init($('#js-scroll-nav'), {
          duration: 700
        });

        // initialization of masonry.js
        $('.masonry-grid').imagesLoaded().then(function () {
          $('.masonry-grid').masonry({
            columnWidth: '.masonry-grid-sizer',
            itemSelector: '.masonry-grid-item',
            percentPosition: true
          });
        });
      });

      $(window).on('resize', function () {
        setTimeout(function () {
          $.HSCore.components.HSTabs.init('[role="tablist"]');
        }, 200);
      });
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAtt1z99GtrHZt_IcnK-wryNsQ30A112J0&callback=initMap" async></script>
 

                    <script  src="{% static 'uni-theme/vendor/appear.js' %}"></script>
                    <script  src="{% static 'uni-theme/vendor/custombox/custombox.min.js' %}"></script>

                    <!-- JS Unify -->
                    <script  src="{% static '2024/js/components/hs.modal-window.js' %}"></script>

                    <!-- JS Plugins Init. -->
                    <script >
                      $(document).on('ready', function () {
                        // initialization of popups
                        $.HSCore.components.HSModalWindow.init('[data-modal-target]');
                      });
                    </script>


                    <script >
                      $(document).on('ready', function () {
                        // initialization of autonomous popups
                        $.HSCore.components.HSModalWindow.init('.js-autonomous-popup', {
                          autonomous: true
                        });
                      });
                    </script>
 


 <script  src="{% static 'uni-theme/vendor/popper.js/popper.min.js' %}"></script>

  <!-- JS Implementing Plugins -->
  <script  src="{% static 'uni-theme/vendor/appear.js' %}"></script>

  <!-- JS Unify -->
  <script  src="{% static '2024/js/components/hs.onscroll-animation.js' %}"></script>

  <!-- JS Plugins Init. -->
  <script >
    $(document).ready(function () {
      // initialization of scroll animation
      $.HSCore.components.HSOnScrollAnimation.init('[data-animation]');
    });
  </script>

  <!-- JS Unify -->
  <script  src="{% static '2024/js/components/hs.tabs.js' %}"></script>

  <!-- JS Plugins Init. -->
  <script >
    $(document).on('ready', function () {
      // initialization of tabs
      $.HSCore.components.HSTabs.init('[role="tablist"]');
    });

    $(window).on('resize', function () {
      setTimeout(function () {
        $.HSCore.components.HSTabs.init('[role="tablist"]');
      }, 200);
    });
    
  </script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      // Select all label elements in the form and apply inline styles
      document.querySelectorAll('form label').forEach(function(label) {
        label.style.fontWeight = 'bold';
      });
    });
  </script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      // Select all help text elements in the form and apply inline styles
      document.querySelectorAll('.help-block').forEach(function(helpText) {
        helpText.style.fontSize = '0.3rem'; // Sets the font size smaller
      });
    });
  </script>
  <style>
    /* Targeting help text within form */
    .form-help-text {
      font-size: 0.8rem; /* Adjust the font size as needed */
    }
  </style>
  
  <script>
    function goBack() {
      window.history.back();
    }
    </script>
  
      <script >
        $(document).on('ready', function () {
          // initialization of carousel
          $.HSCore.components.HSCarousel.init('.js-carousel');
        });
      </script>
</body>
</html>

pycons-site/templates/tem-nav.html
{% load  %}
{% load static base_extras %}

 <!-- Header -->
 <header id="js-header" class="u-header u-header--abs-top u-header--show-hide u-header--change-logo u-header--change-appearance" data-header-fix-moment="500" data-header-fix-effect="slide">
  <div class="u-header__section u-header__section--dark g-bg-black-opacity-0_7 g-py-10" data-header-fix-moment-exclude="u-header__section--dark g-bg-black-opacity-0_7 g-py-10" data-header-fix-moment-classes="u-header__section--light g-bg-white-opacity-0_7 u-shadow-v18 g-py-0">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <!-- Responsive Toggle Button -->
        <button class="navbar-toggler navbar-toggler-right btn g-line-height-1 g-brd-none g-pa-0 g-pos-abs g-top-3 g-right-0" type="button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="navBar" data-toggle="collapse" data-target="#navBar">
          <span class="hamburger hamburger--slider">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
          </span>
          </span>
        </button>
        <!-- End Responsive Toggle Button -->

        <!-- Logo -->
        <a href="/" class="navbar-brand u-header__logo">
          <img class="u-header__logo-img u-header__logo-img--main" src="{% static '2024/img/logo-w.png' %}" alt="Image Description">

          <img class="u-header__logo-img" src="{% static '2024/img/logo-w.png' %}" alt="Image Description">
        </a>
        <!-- End Logo -->

        {% if user.is_authenticated %}
       
         <!-- Navigation -->
         <div class="collapse navbar-collapse align-items-center flex-sm-row g-pt-10 g-pt-5--lg" id="navBar">
          <ul class="navbar-nav text-uppercase g-font-weight-600 ml-auto">
            <li class="nav-item g-mx-20--lg">
              <a href="/2024" class="nav-link px-0">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown g-mx-20--lg">
              <a href="#" class="nav-link dropdown-toggle g-px-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
              <!-- Submenu (Bootstrap) -->
              <ul class="dropdown-menu rounded-0 g-text-transform-none g-brd-none g-brd-top g-brd-primary g-brd-top-2 g-mt-20 g-mt-10--lg--scrolling">
                <li class="dropdown-item ">
                  <a class="nav-link g-px-0 g-color-black" href="/2024/about/">About Us</a>
                </li>
                <li class="dropdown-item">
                  <a class="nav-link g-px-0 g-color-black" href="/2024/coc/">Code of Conduct</a>
                </li> 
                <li class="dropdown-item">
                  <a class="nav-link g-px-0 g-color-black" href="/2024/about/team/">Team</a>
                </li> 
              </ul>
              <!-- End Submenu (Bootstrap) -->
            </li>
            <li class="nav-item g-mx-20--lg">
              <a href="#" class="nav-link px-0">Speakers</a>
            </li>
            <li class="nav-item g-mx-20--lg">
              <a href="#" class="nav-link px-0">Schedule</a>
            </li>
            <li class="nav-item g-mx-20--lg">
              <a href="https://pyconafrica.blogspot.com/" target="/" class="nav-link px-0">Blog</a>
            </li> 
            <li class="nav-item dropdown g-mx-20--lg">
              <a href="#" class="nav-link dropdown-toggle g-px-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Sponsor</a>
              <!-- Submenu (Bootstrap) -->
              <ul class="dropdown-menu rounded-0 g-text-transform-none g-brd-none g-brd-top g-brd-primary g-brd-top-2 g-mt-20 g-mt-10--lg--scrolling">
                <li class="dropdown-item ">
                  <a class="nav-link g-px-0 g-color-black" href="/2024/sponsor-us/">Sponsor Us</a>
                </li>
                <li class="dropdown-item">
                  <a class="nav-link g-px-0 g-color-black " href="/2024/our-sponsors/">Our Sponsors</a>
                </li> 
              </ul>
              <!-- End Submenu (Bootstrap) -->
            </li>
            <li class="nav-item dropdown g-mx-20--lg">
              <a href="#" class="nav-link dropdown-toggle g-px-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Past</a>
              <!-- Submenu (Bootstrap) -->
              <ul class="dropdown-menu rounded-0 g-text-transform-none g-brd-none g-brd-top g-brd-primary g-brd-top-2 g-mt-20 g-mt-10--lg--scrolling">
                <li class="dropdown-item">
                  <a class="nav-link g-px-0 g-color-black" href="/2020/">2020</a>
                </li>
                <li class="dropdown-item">
                  <a class="nav-link g-px-0 g-color-black" href="/2019/">2019</a>
                </li> 
              </ul>
              <!-- End Submenu (Bootstrap) -->
            </li> 
          </ul>

          
        {% if user.is_authenticated %} 
        <div class="col-auto">
         
 
          <div class="nav-item dropdown  ">
            <a href="#" class="nav-link dropdown-toggle g-px-5" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">  
             {% if request.user.user_profile.profile_image %} 
              <span class="d-inline-block g-pos-rel g-mr-20 g-mb-20"> 
                <img class="rounded-circle g-width-50 g-height-50" src="{{ request.user.user_profile.profile_image.url }}" alt="avatar"> Hi {% if request.user.user_profile %}{{ request.user.user_profile.name }}  {% else %}@{{ request.user.username }}{% endif %} 😊
              </span> 
               {% else %}
  
              <span class="d-inline-block g-pos-rel g-mr-20 g-mb-20"> 
              <img class="g-width-40 g-height-40 rounded-circle mCS_img_loaded" src="/robohash/{% firstof user.get_short_name user.get_username|capfirst %}/?width=120&height=120" alt="Image Description">  Hi {% if request.user.user_profile %}{{ request.user.user_profile.name }}  {% else %}@{{ request.user.username }}{% endif %} 😊
            </span> 
              {% endif %}  
              </a>
              
           
            <!-- Submenu (Bootstrap) -->
            <ul class="dropdown-menu rounded-0 g-text-transform-none  g-brd-none g-brd-top g-brd-primary g-brd-top-2 g-mt-20 g-mt-10--lg--scrolling">
              <div class="d-flex flex-row align-items-center text-center justify-content-between g-letter-spacing-1 g-mb-15"> 
                <strong class="g-color-black g-font-weight-600 g-font-size-18"><small  ti  data-toggle="tooltip-show" data-placement="left" title="Glad to have you here {% if request.user.user_profile %}{{ request.user.user_profile.name }} {% else %}@{{ request.user.username }}{% endif %}">&nbsp;&nbsp;&nbsp;&nbsp;{% time_of_day %}</small> </strong>
                </div>
              <li class="dropdown-item  g-color-black"> 
                 <a href="{% url 'profiles:profile_home' %}" class="nav-link g-color-black g-color-dark--hover g-text-underline--none--hover g-font-size-16"><i class="far fa-address-card g-color-black g-font-size-16"></i> My Profile</a>
              </li>
              {% if request.user.is_superuser %}
              <li class="dropdown-item g-color-black">
                <a href="/organizers/" target="/" class="nav-link g-color-black g-color-dark--hover g-text-underline--none--hover g-font-size-16"><i class="fas fa-users-crown  g-color-black g-font-size-16"></i> Admin Dashboard</a>
              </li>  
                  {% endif %}
                   
              <li class="dropdown-item g-color-black">
                <form action="/accounts/logout/" method="post" style="display: inline;">
                  {% csrf_token %}
                  <button type="submit" class="nav-link g-color-black g-color-dark--hover g-text-underline--none--hover g-font-size-16" style="background: none; border: none; padding: 0; cursor: pointer;">
                    &nbsp;&nbsp;&nbsp;<i class="fal fa-sign-out-alt g-color-black g-font-size-16"></i> Log out
                  </button>
                </form>
              </li>
   
            </ul>
            <!-- End Submenu (Bootstrap) -->
          </div> 
  

        </div>
          {% else %} 
        <div class="col-auto g-pos-rel">
          <ul class="list-inline g-overflow-hidden g-pt-1 g-mx-minus-4 mb-0">
              
            <li class="list-inline-item g-mx-4">
              <a class="g-color-white g-color-yellow--hover g-text-underline--none--hover" href="/accounts/login/">Login</a>
            </li>
            <li class="list-inline-item g-mx-4">|</li>
            <li class="list-inline-item g-mx-4">
              <a class="g-color-white g-color-yellow--hover g-text-underline--none--hover" href="/accounts/signup/">Signup</a>
            </li>
          </ul>
        </div>
      {% endif %} 

        </div>
        <!-- End Navigation -->

 
 
        {% else %}
 
  <!-- Navigation -->
  <div class="collapse navbar-collapse align-items-center flex-sm-row g-pt-10 g-pt-5--lg" id="navBar">
    <ul class="navbar-nav text-uppercase g-font-weight-600 ml-auto">
      <li class="nav-item g-mx-20--lg">
        <a href="/" class="nav-link px-0">Home <span class="sr-only">(current)</span></a>
      </li> 
      <li class="nav-item g-mx-20--lg">
        <a href="https://pyconafrica.blogspot.com/" target="/" class="nav-link px-0">Blog</a>
      </li>  
      <li class="nav-item dropdown g-mx-20--lg">
        <a href="#" class="nav-link dropdown-toggle g-px-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Past</a>
        <!-- Submenu (Bootstrap) -->
        <ul class="dropdown-menu rounded-0 g-text-transform-none g-brd-none g-brd-top g-brd-primary g-brd-top-2 g-mt-20 g-mt-10--lg--scrolling">
          <li class="dropdown-item">
            <a class="nav-link g-px-0 g-color-black" href="/2020/">2020</a>
          </li>
          <li class="dropdown-item">
            <a class="nav-link g-px-0 g-color-black" href="/2019/">2019</a>
          </li> 
        </ul>
        <!-- End Submenu (Bootstrap) -->
      </li> 
    </ul>

     

  </div>
  <!-- End Navigation -->

      
        {% endif %}
      
        

           
      </div>
    </nav>
  </div>
</header>
<!-- End Header -->


 